### ISSUE TITLE
Endless loop of 401 errors with Remix

### ISSUE THREAD

**Issue by arjunyel** [clerk/javascript#2381]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction / Replay Link

https://github.com/arjunyel/clerk-remix-loop

### Publishable key

pk_test_Y2xlcmsuaW50ZW5zZS5qYXktOTEubGNsLmRldiQ

### Description

**Steps to reproduce:**

1. Add Clerk keys to `.dev.vars`

   ```env
   CLERK_PUBLISHABLE_KEY=
   CLERK_SECRET_KEY=
   ```

1. `npm install`

1. `npm run dev`

1. Navigate to [http://localhost:8788/](http://localhost:8788/) in browser

Should see endless loop of 401 errors

**Expected behavior:**

Should show the sign in button

**Actual behavior:**

Endless loop of refreshes with the server throwing 401 errors

### Environment

```Shell
System:
    OS: macOS 14.1.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.29 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/21918_1702679261408/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/21918_1702679261408/bin/npm
    bun: 1.0.14 - /usr/local/bin/bun
  Browsers:
    Safari: 17.1.2
  npmPackages:
    @clerk/remix: ^3.1.11 => 3.1.11 
    @cloudflare/workers-types: ^4.20231121.0 => 4.20231121.0 
    @remix-run/cloudflare: ^2.4.0 => 2.4.0 
    @remix-run/cloudflare-pages: ^2.4.0 => 2.4.0 
    @remix-run/css-bundle: ^2.4.0 => 2.4.0 
    @remix-run/dev: ^2.4.0 => 2.4.0 
    @remix-run/react: ^2.4.0 => 2.4.0 
    @types/react: ^18.2.45 => 18.2.45 
    @types/react-dom: ^18.2.17 => 18.2.17 
    @typescript-eslint/eslint-plugin: ^6.14.0 => 6.14.0 
    eslint: ^8.55.0 => 8.55.0 
    eslint-config-prettier: ^9.1.0 => 9.1.0 
    eslint-plugin-import: ^2.29.1 => 2.29.1 
    eslint-plugin-jsx-a11y: ^6.8.0 => 6.8.0 
    eslint-plugin-react: ^7.33.2 => 7.33.2 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    isbot: ^3.7.1 => 3.7.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
    wrangler: 3.21.0 => 3.21.0
```

**Comment by smorimoto** [comment]
I'm also just experiencing this... If you manually add a slash to the end of the URI, the loop ends.

**Comment by ChronicStone** [comment]
I seem to be experiencing the same thing since the start of the day. Everything was working fine yesterday.

Production not impacted, only dev server

**Comment by MrDogeBro** [comment]
I am also experiencing this issue, but adding the slash at the end of the URI temporarily fixes it for me as well. Any word on why this is happening or what/when a fix can be expected? It's not making a great developer experience right now...

**Comment by smorimoto** [comment]
With the latest Wrangler and SDK combinations, this problem seems to disappear.

**Comment by arjunyel** [comment]
Yes appears to be fixed now, thank you!
