### ISSUE TITLE
Constantly getting redirection from clerk in Next app

### ISSUE THREAD

**Issue by RSAK56** [clerk/javascript#3980]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/RSAK56/form-craft

### Publishable key

pk_test_bWVldC1raXdpLTc1LmNsZXJrLmFjY291bnRzLmRldiQ

### Description

The issue I'm facing is constantly redirecting the login page even when logged into the application. This is the log shown in the browser console of my Next js application:
`The <SignIn/> component cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the `after SignIn` URL instead. (This notice only appears in development)`

Not sure what could be the possible outcome and solution for this. But this issue was already reported here as well:
[link](https://github.com/clerk/clerk-next-app-router-starter/issues/4)

### Environment

```Shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 127.57 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.5
  npmPackages:
    @clerk/nextjs: ^5.3.1 => 5.3.1 
    @google/generative-ai: ^0.14.0 => 0.14.0 
    @neondatabase/serverless: ^0.9.4 => 0.9.4 
    @radix-ui/react-alert-dialog: ^1.1.1 => 1.1.1 
    @radix-ui/react-checkbox: ^1.1.1 => 1.1.1 
    @radix-ui/react-dialog: ^1.1.1 => 1.1.1 
    @radix-ui/react-label: ^2.1.0 => 2.1.0 
    @radix-ui/react-popover: ^1.1.1 => 1.1.1 
    @radix-ui/react-progress: ^1.1.0 => 1.1.0 
    @radix-ui/react-radio-group: ^1.2.0 => 1.2.0 
    @radix-ui/react-select: ^2.1.1 => 2.1.1 
    @radix-ui/react-slot: ^1.1.0 => 1.1.0 
    @radix-ui/react-tooltip: ^1.1.2 => 1.1.2 
    @types/node: ^20 => 20.14.8 
    @types/react: ^18 => 18.3.3 
    @types/react-dom: ^18 => 18.3.0 
    class-variance-authority: ^0.7.0 => 0.7.0 
    clsx: ^2.1.1 => 2.1.1 
    daisyui: ^4.12.8 => 4.12.8 
    dotenv: ^16.4.5 => 16.4.5 
    drizzle-kit: ^0.22.7 => 0.22.7 
    drizzle-orm: ^0.31.2 => 0.31.2 
    eslint: ^8 => 8.57.0 
    eslint-config-next: 14.2.4 => 14.2.4 
    framer-motion: ^11.3.2 => 11.3.2 
    lucide-react: ^0.396.0 => 0.396.0 
    moment: ^2.30.1 => 2.30.1 
    next: 14.2.4 => 14.2.4 
    postcss: ^8 => 8.4.38 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    react-hot-toast: ^2.4.1 => 2.4.1 
    tailwind-merge: ^2.3.0 => 2.3.0 
    tailwindcss: ^3.4.1 => 3.4.4 
    tailwindcss-animate: ^1.0.7 => 1.0.7 
    typescript: ^5 => 5.5.2
```

**Comment by vanshrl9ine** [comment]
Hey maybe your repo is private?

**Comment by RSAK56** [comment]
> Hey maybe your repo is private?
> 
Yeah, it is since it's a personal product I'm working on. Not yet ready for open source contribution. But this issue still resides. Is there any other way that I can provide details?

**Comment by vanshrl9ine** [comment]
With Limited information I can suggest you to look into your middleware.ts file or use alternative methods like Convex+Clerk

**Comment by wobsoriano** [comment]
Hey, thanks for reaching out! I see that your repo is private. Would you be able to provide a minimal reproduction at least? 

Thank you!

**Comment by RSAK56** [comment]
Will try to create a minimal reproduction link or maybe update my repo link to public for now.

**Comment by RSAK56** [comment]
> Hey, thanks for reaching out! I see that your reproduction repo is private. Would you be able to provide a minimal reproduction at least?
> 
> Thank you!

Hey following is the link for minimal reproduction:
[https://github.com/RSAK56/clerk-auth-app](https://github.com/RSAK56/clerk-auth-app)

Clone it using HTTPS or SSH as you feel easy and you'll need the following keys mentioned in the readme and .env.example. Once you're done with the basic setup you can open parallel windows on your vscode and execute the following commands in each:
1. `npm run dev`
2. `npm run db:studio`


Steps to reproduce:
1. You can login to the application using login button and use clerk google auth. _(Note: Using an email will not link to the same steps. Since the issue was with the Google auth, so we can be specific to the steps for reproduction of issues)_
2. You will see a dashboard button and avatar on the top header after being successfully logged into the app.
3. Once you are there click on the **Dashboard** button and see the application take you back to the auth screen
4. In your browser console after inspect, you'll be able to see this message:
`The <SignIn/> component cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the after SignIn URL instead. (This notice only appears in development)`

**Comment by RSAK56** [comment]
Okay so turns out that my mac's date and time were not as per my current location as soon as I updated my date and time based on my current location. It started to work. I just cross-verified by changing it to a different one again.
