### ISSUE TITLE
"tauri:" is not a valid protocol

### ISSUE THREAD

**Issue by ryansteil-pl** [clerk/javascript#4667]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

n/a

### Publishable key

n/a

### Description

I'm using Clerk from within a [tauri](https://tauri.app/) app.

When building for production, I'm getting the following warning in the developer console of the webview

`Clerk: "tauri:" is not a valid protocol. Redirecting to "/" instead. If you think this is a mistake, please open an issue.`

due to missing the protocol here

https://github.com/clerk/javascript/blob/b0d165aa940f1f87ca95045188b6627f3519cd7e/packages/clerk-js/src/utils/windowNavigate.ts#L3-L9

### Environment

```Shell
n/a
```

**Comment by jacekradko** [comment]
@ryansteil-pl Thanks for filling this issue. We heard similar feedback from other users and will be releasing a fix in the near future that will allow you specify additional protocols that your app supports. For reference, here is the PR https://github.com/clerk/javascript/pull/4705

**Comment by louis030195** [comment]
i implemented clerk in tauri here if useful

https://github.com/mediar-ai/screenpipe/tree/main/screenpipe-app-tauri
