### ISSUE TITLE
@clerk/react-router using CloudFare Template

### ISSUE THREAD

**Issue by LydiaF** [clerk/javascript#4759]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/lydiaf/importbug

### Publishable key

-

### Description

**Steps to reproduce:**

1. Open root.tsx, and comment in and out the import rootAuthLoader, you can see app stops loading

**Expected behavior:**

App loads

**Actual behavior:**

App does not load with input

--

I am just experiencing this with Cloudflare template, not Vercel template. 

### Environment

```Shell
-
```

**Comment by LekoArts** [comment]
Hello, thanks for the issue!

I've ran your reproduction and can confirm that it it fails with `require is not defined`.

```shell
[vite-node-miniflare error]
ReferenceError: require is not defined
    at /Users/lejoe/code/playground/importbug/node_modules/snakecase-keys/index.js:3:13
```

`@clerk/react-router` imports `@clerk/backend` which itself imports `snakecase-keys`. However, this is a quite common error with Vite bundling. `snakecase-keys` is CJS and you can't use `require` in ESM builds. So you'll need to adjust the [optimizeDeps.include](https://vite.dev/config/dep-optimization-options.html#optimizedeps-include) list.

I've got it working like this:
1. Change the template by following this PR change: https://github.com/remix-run/react-router-templates/pull/6
2. Add `snakecase-keys` and `cookie` to the list

	```diff
	    optimizeDeps: {
	      include: [
	        "react",
	        "react/jsx-runtime",
	        "react/jsx-dev-runtime",
	        "react-dom",
	        "react-dom/server",
	        "react-router",
	+       "snakecase-keys",
	+       "cookie"
	      ],
	    },
	```
