### ISSUE TITLE
Peer dependency unmet when using react 19 with react router 7

### ISSUE THREAD

**Issue by sanisoclem** [clerk/javascript#4825]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Description

react 19 is not included in peer dependencies for `@clerk/react-router 0.1.5`. 

**Steps to reproduce:**

1. Create new react router app `npx create-react-router@latest my-react-router-app`
2. Install Clerk `pnpm add @clerk/react-router`

**Expected behavior:**

Clerk installed without warnings.

**Actual behavior:**

> Issues with peer dependencies found

![image](https://github.com/user-attachments/assets/1b2d6964-0e7c-4ca8-a35c-8f7ff6275074)

### Environment

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 39.93 GB / 63.14 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @clerk/react-router: ^0.1.5 => 0.1.5
    @eslint/js: ^9.17.0 => 9.17.0
    @phosphor-icons/react: ^2.1.7 => 2.1.7
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/express: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    @tailwindcss/container-queries: ^0.1.1 => 0.1.1
    @tailwindcss/forms: ^0.5.9 => 0.5.9
    @types/node: ^22 => 22.10.2
    @types/react: ^19.0.1 => 19.0.1
    @types/react-dom: ^19.0.1 => 19.0.2
    autoprefixer: ^10.4.20 => 10.4.20
    compression: ^1.7.5 => 1.7.5
    cross-env: ^7.0.3 => 7.0.3
    eslint: ^9.17.0 => 9.17.0
    eslint-config-prettier: ^9.1.0 => 9.1.0
    eslint-plugin-react: ^7.37.2 => 7.37.2
    express: ^4.21.2 => 4.21.2
    globals: ^15.13.0 => 15.13.0
    helmet: ^8.0.0 => 8.0.0
    isbot: ^5.1.17 => 5.1.18
    postcss: ^8.4.49 => 8.4.49
    prettier: ^3.4.2 => 3.4.2
    prettier-plugin-tailwindcss: ^0.6.9 => 0.6.9
    react: ^19.0.0 => 19.0.0
    react-dom: ^19.0.0 => 19.0.0
    react-router: ^7.0.2 => 7.0.2
    tailwindcss: ^3.4.16 => 3.4.17
    typescript: ^5.7.2 => 5.7.2
    typescript-eslint: ^8.18.1 => 8.18.1
    vite: ^5.4.11 => 5.4.11
    vite-tsconfig-paths: ^5.1.4 => 5.1.4
    zod: ^3.24.1 => 3.24.1
```

**Comment by panteliselef** [comment]
Hey @sanisoclem thanks for reaching out. This is an issue with swr dependencies. One day ago [2.3.0](https://github.com/vercel/swr/commit/f22b2744566d46799f1274a4641cdb221e4871a3) was release which addresses the issue. Simply try to update your dependencies or reinstall the packages. Clerk is using `^2.2.0` which with a fresh install will get you the `2.3.0` version.

Happy hacking and happy holidays.
